### ISSUE TITLE
Does not build any more?

### ISSUE THREAD

**Issue by sb-cecilialiu** [tzolov/playground-flight-booking#3]
Not sure why, it was built and running fine a couple of weeks ago, but now I got build issue:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /ai-openai-flight-service/src/main/java/ai/spring/demo/ai/playground/services/LoggingAdvisor.java:[5,42] cannot find symbol
  symbol:   class AdvisedRequest
  location: package org.springframework.ai.chat.client
.....
[INFO] 4 errors

**Comment by lopatamd** [comment]
comment out the looggingAdvisor for now

**Comment by sb-cecilialiu** [comment]
@lopatamd Thanks so much for the advice! I can certainly do that. I was just wondering why AdvisedRequest is not in org.springframework.ai.chat.client package any more?

**Comment by tzolov** [comment]
Yep M3 release came with couple of compatibility changes around the Advisors. Will fix it shortly

**Comment by sb-cecilialiu** [comment]
@tzolov Thank you so much for the info!!
